name: Compile production files

on:
  workflow_dispatch:
  push:


jobs:
 
  compile-production-files:
    runs-on: ubuntu-latest
    # needs: esphome-firmware-validation

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Generate full documentation
        uses: INTI-CMNB/KiBot@v2_k7
        with:
          dir: .
          config: .kibot/full-outputs.kibot.yaml
          schema: electronics/driver-board.kicad_sch
          board: electronics/driver-board.kicad_pcb
          install3D: yes

      - name: Fix file permissions for generated files
        run: sudo chown -R $(id -u):$(id -g) ./exports

      - name: Get current date and time
        id: gitstamp
        # https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
        # run: echo "::set-output name=datehash::$(git log -1 --format='%as')-$(git log -1 --pretty=format:%h)"
        run: echo "datehash=$(git log -1 --format='%as')-$(git log -1 --pretty=format:%h)" >> $GITHUB_OUTPUT
        
      # TODO: dynamic expand all images with date and commit hash
      # - name: Copy renders to static folder
      #   run: |
      #     set -e
      #     FONT=".github/artifacts/fonts/RobotoMono-Bold.ttf"
      #     set -v
      #     LABEL="`${{ steps.date.outputs.date }}`\n`git rev-parse --short HEAD`"
      #     convert -background black -fill white -pointsize 12 -font "$FONT" -size 300x36 label:"$LABEL" -bordercolor black -border 3 exports/renders/*.png +swap -append exports/renders/*.png

      - name: Commit renders to static folder
        run: |
          mkdir -p static/images/
          cp -r exports/renders/*.png static/images/        
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f static/images
          git commit -m "latest renders"
          git push

      - name: Archive project artifacts
        uses: actions/upload-artifact@v3
        with:
          name: driver-board-${{ steps.gitstamp.outputs.datehash }}
          if-no-files-found: error
          path: |

            # Documentations
            exports/driver-board-schematic-*.pdf
            exports/driver-board-pcb-layers-*.pdf
            exports/driver-board-pcb-layers-*.pdf
            exports/driver-board-design-report-*.txt

            exports/datasheets
            exports/driver-board-ibom-*.html
            exports/driver-board-kicost-*.xlsx

            # Production files
            exports/gerbers/*.zip
            exports/driver-board-bom-*.csv
            
            ## Extras
            exports/renders/*.png
            exports/renders/*.jpg
            exports/driver-board-*.step
            exports/project
